export const coursesStatus =  [{
     __typename: "CoursesStatusObj",
     courseCode: "950702",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "950701",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082020",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082021",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082022",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082023",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "081420",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "951604",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082024",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "950703",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082025",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "950605",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082026",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "951602",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "950704",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082028",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082027",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "950309",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082030",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "951603",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "950310",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "082098",
     completionCode: "P"
   }, {
     __typename: "CoursesStatusObj",
     courseCode: "K08-INT-HABPROF",
     completionCode: "P"
   }];

export const _user1 = {
  __typename: "UserObject",
	id: 1,
	username: "pipe",
	avatar: null,
	careerPlan: null
};

export const _user2 = {
  __typename: "UserObject",
	id: 1,
	username: "pipe",
	avatar: null,
	careerPlan: {
		code: "K08",
		name: "Ingeniería en sistemas de Información [K08] (UTN - FRBA)",
		__typename: "CareerPlanObj"
	}
};

export const careerPlans = [{
  __typename: "CareerPlanObj",
  code: "K08",
  name: "Ingeniería en sistemas de Información [K08] (UTN - FRBA)"
},
{
  __typename: "CareerPlanObj",
  code: "K08-INT",
  name: "Analista Universitario en Sistemas (UTN - FRBA)"
}];

export const completionStatuses = [{
   __typename: "CompletionStatusObj",
   status: "P",
   name: "Pendiente"
 }, {
   __typename: "CompletionStatusObj",
   status: "E",
   name: "Cursando"
 }, {
   __typename: "CompletionStatusObj",
   status: "C",
   name: "Firmada"
 }, {
   __typename: "CompletionStatusObj",
   status: "F",
   name: "Aprobada"
}];

export const coursePrerrequisites = [{
		  __typename: "CoursePrerrequisitesObj",
			courseCode: "082024",
			prerrequisiteCode: "082023",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082024",
			prerrequisiteCode: "082021",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082024",
			prerrequisiteCode: "082023",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082024",
			prerrequisiteCode: "082021",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950703",
			prerrequisiteCode: "950701",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950703",
			prerrequisiteCode: "950702",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950703",
			prerrequisiteCode: "950701",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950703",
			prerrequisiteCode: "950702",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950704",
			prerrequisiteCode: "950701",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950704",
			prerrequisiteCode: "950702",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950704",
			prerrequisiteCode: "950701",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "950704",
			prerrequisiteCode: "950702",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082025",
			prerrequisiteCode: "082020",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082025",
			prerrequisiteCode: "082021",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082025",
			prerrequisiteCode: "082020",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082025",
			prerrequisiteCode: "082021",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082026",
			prerrequisiteCode: "082020",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082026",
			prerrequisiteCode: "082021",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082026",
			prerrequisiteCode: "082020",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082026",
			prerrequisiteCode: "082021",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082028",
			prerrequisiteCode: "082024",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082028",
			prerrequisiteCode: "082026",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082028",
			prerrequisiteCode: "082020",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082028",
			prerrequisiteCode: "082021",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082028",
			prerrequisiteCode: "082023",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082028",
			prerrequisiteCode: "082024",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082028",
			prerrequisiteCode: "082026",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082024",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082025",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082026",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082020",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082021",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082023",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082024",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082025",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082030",
			prerrequisiteCode: "082026",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082027",
			prerrequisiteCode: "082020",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082027",
			prerrequisiteCode: "082021",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082027",
			prerrequisiteCode: "082022",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082027",
			prerrequisiteCode: "082020",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082027",
			prerrequisiteCode: "082021",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "082027",
			prerrequisiteCode: "082022",
			completionCode: "F",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "951603",
			prerrequisiteCode: "951602",
			completionCode: "C",
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseCode: "951603",
			prerrequisiteCode: "951602",
			completionCode: "F",
			type: "C"
		}];

  export const careerPlan = {
			__typename: "CareerPlanObj",
      code: "K08-INT",
			name: "Analista Universitario en Sistemas (UTN - FRBA)",
			courses: [{
				code: "950702",
				name: "\u00c1lgebra y Geometr\u00eda Anal\u00edtica",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "950701",
				name: "An\u00e1lisis Matem\u00e1tico I",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082020",
				name: "Matem\u00e1tica Discreta",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082021",
				name: "Algoritmos y Estructura de Datos",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082022",
				name: "Arquitectura de Computadoras",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082023",
				name: "Sistemas y Organizaciones",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "081420",
				name: "Qu\u00edmica",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "951604",
				name: "Ingenier\u00eda y Sociedad",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082024",
				name: "An\u00e1lisis de Sistemas",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "950703",
				name: "An\u00e1lisis Matem\u00e1tico II",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "082025",
				name: "Sintaxis y Sem\u00e1ntica de los Lenguajes",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "950605",
				name: "F\u00edsica I",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "082026",
				name: "Paradigmas de Programaci\u00f3n",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "951602",
				name: "Ingl\u00e9s I",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "950704",
				name: "Probabilidad y Estad\u00edstica",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "082028",
				name: "Dise\u00f1o de Sistemas",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "082027",
				name: "Sistemas Operativos",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "950309",
				name: "Econom\u00eda",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "082030",
				name: "Gesti\u00f3n de Datos",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "951603",
				name: "Ingl\u00e9s II",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "950310",
				name: "Legislaci\u00f3n",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "082098",
				name: "Comunicaciones y Redes",
				year: 4,
				__typename: "CourseObj"
			}, {
				code: "K08-INT-HABPROF",
				name: "Habilitac\u00f3n Profesional (Titulo intermedio)",
				year: 4,
				__typename: "CourseObj"
			}]
};
