export const coursesStatus =  [{
			__typename: "CoursesStatusObj",
			courseCode: "950702",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "950701",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082020",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082021",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082022",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082023",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "081420",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "951604",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082024",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "950703",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082025",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "950605",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082026",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "951602",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "950704",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082028",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082027",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "950309",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082030",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "951603",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "950310",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "082098",
			completionId: 1
		}, {
			__typename: "CoursesStatusObj",
			courseCode: "K08-INT-HABPROF",
		completionId: 1
}];

export const _user1 = {
  __typename: "UserObject",
	id: 1,
	username: "pipe",
	avatar: null,
	careerPlan: null
};

export const _user2 = {
  __typename: "UserObject",
	id: 1,
	username: "pipe",
	avatar: null,
	careerPlan: {
		code: "K08",
		name: "Ingeniería en sistemas de Información [K08] (UTN - FRBA)",
		__typename: "CareerPlanObj"
	}
};

export const careerPlans = [{
  __typename: "CareerPlanObj",
  code: "K08",
  name: "Ingeniería en sistemas de Información [K08] (UTN - FRBA)"
},
{
  __typename: "CareerPlanObj",
  code: "K08-INT",
  name: "Analista Universitario en Sistemas (UTN - FRBA)"
}];

export const completionStatuses = [{
			__typename: "CompletionStatusObj",
			id: 1,
			name: "Pendiente"
		}, {
			__typename: "CompletionStatusObj",
			id: 2,
			name: "Cursando"
		}, {
			__typename: "CompletionStatusObj",
			id: 3,
			name: "Firmada"
		}, {
			__typename: "CompletionStatusObj",
			id: 4,
			name: "Aprobada"
}];

export const coursePrerrequisites = [{
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 7,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 7,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 1,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 3,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 3,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 4,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 4,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 1,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 3,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 3,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 4,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 5,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 7,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 9,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 14,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 4,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 6,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 6,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 1,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 13,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 13,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 22,
			prerrequisiteId: 15,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 22,
			prerrequisiteId: 15,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 9,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 12,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 14,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 4,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 5,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 7,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 12,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 1,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 3,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 11,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 17,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 18,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 20,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 6,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 9,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 14,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 15,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 17,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 20,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 16,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 17,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 21,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 9,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 12,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 14,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 17,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 21,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 8,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 23,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 19,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 8,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 6,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 11,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 19,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 1,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 3,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 13,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 6,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 19,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 18,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 28,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 4,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 5,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 6,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 19,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 28,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 16,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 23,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 16,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 23,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 30,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 31,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 23,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 31,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 25,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 30,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 20,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 23,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 25,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 25,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 30,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 31,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 20,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 23,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 25,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 31,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 24,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 25,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 26,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 29,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 2,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 20,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 21,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 10,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 21,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 22,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 28,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 2,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 3,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 6,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 7,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 8,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 10,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 12,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 13,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 15,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 17,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 19,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 20,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 21,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 22,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 24,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 25,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 26,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 27,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 28,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 29,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 31,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 33,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 34,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 35,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 17,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 21,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 37,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 9,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 12,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 14,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 22,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 17,
			completionId: 7,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 21,
			completionId: 7,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 37,
			completionId: 7,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 12,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 22,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 11,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 1,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 3,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 6,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 13,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
	}];

  export const careerPlan = {
			__typename: "CareerPlanObj",
      code: "K08-INT",
			name: "Analista Universitario en Sistemas (UTN - FRBA)",
			courses: [{
				code: "950702",
				name: "\u00c1lgebra y Geometr\u00eda Anal\u00edtica",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "950701",
				name: "An\u00e1lisis Matem\u00e1tico I",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082020",
				name: "Matem\u00e1tica Discreta",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082021",
				name: "Algoritmos y Estructura de Datos",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082022",
				name: "Arquitectura de Computadoras",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082023",
				name: "Sistemas y Organizaciones",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "081420",
				name: "Qu\u00edmica",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "951604",
				name: "Ingenier\u00eda y Sociedad",
				year: 1,
				__typename: "CourseObj"
			}, {
				code: "082024",
				name: "An\u00e1lisis de Sistemas",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "950703",
				name: "An\u00e1lisis Matem\u00e1tico II",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "082025",
				name: "Sintaxis y Sem\u00e1ntica de los Lenguajes",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "950605",
				name: "F\u00edsica I",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "082026",
				name: "Paradigmas de Programaci\u00f3n",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "951602",
				name: "Ingl\u00e9s I",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "950704",
				name: "Probabilidad y Estad\u00edstica",
				year: 2,
				__typename: "CourseObj"
			}, {
				code: "082028",
				name: "Dise\u00f1o de Sistemas",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "082027",
				name: "Sistemas Operativos",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "950309",
				name: "Econom\u00eda",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "082030",
				name: "Gesti\u00f3n de Datos",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "951603",
				name: "Ingl\u00e9s II",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "950310",
				name: "Legislaci\u00f3n",
				year: 3,
				__typename: "CourseObj"
			}, {
				code: "082098",
				name: "Comunicaciones y Redes",
				year: 4,
				__typename: "CourseObj"
			}, {
				code: "K08-INT-HABPROF",
				name: "Habilitac\u00f3n Profesional (Titulo intermedio)",
				year: 4,
				__typename: "CourseObj"
			}]
};
