export const coursesStatus = [{
   __typename: "CoursesStatusObj",
   courseId: 36,
   completionId: 5
  },
  {
	__typename: "CoursesStatusObj",
    courseId: 37,
	completionId: 5
  },
  {
	__typename: "CoursesStatusObj",
	courseId: 9,
	completionId: 8
  },
  {
			__typename: "CoursesStatusObj",
			courseId: 12,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 6,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 11,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 16,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 17,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 13,
			completionId: 7
		}, {
			__typename: "CoursesStatusObj",
			courseId: 1,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 2,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 3,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 4,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 5,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 7,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 14,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 15,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 18,
			completionId: 7
		}, {
			__typename: "CoursesStatusObj",
			courseId: 20,
			completionId: 7
		}, {
			__typename: "CoursesStatusObj",
			courseId: 22,
			completionId: 8
		}, {
			__typename: "CoursesStatusObj",
			courseId: 21,
			completionId: 7
}];

export const _user1 = {
  __typename: "UserObject",
	id: 1,
	username: "pipe",
	avatar: null,
	careerPlan: null
};

export const _user2 = {
  __typename: "UserObject",
	id: 1,
	username: "pipe",
	avatar: null,
	careerPlan: {
		id: 2,
		name: "Ingeniería en sistemas de Información [K08] (UTN - FRBA)",
		__typename: "CareerPlanObj"
	}
};

export const careerPlans = [{
  __typename: "CareerPlanObj",
	id: 1,
  name: "Ingeniería en sistemas de Información [K08] (UTN - FRBA)"
},
{
  __typename: "CareerPlanObj",
	id: 2,
  name: "Analista Universitario en Sistemas (UTN - FRBA)"
}];

export const completionStatuses = [{
			__typename: "CompletionStatusObj",
			id: 5,
			name: "Pendiente"
		}, {
			__typename: "CompletionStatusObj",
			id: 6,
			name: "Cursando"
		}, {
			__typename: "CompletionStatusObj",
			id: 7,
			name: "Firmada"
		}, {
			__typename: "CompletionStatusObj",
			id: 8,
			name: "Aprobada"
}];

export const coursePrerrequisites = [{
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 7,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 9,
			prerrequisiteId: 7,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 1,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 3,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 11,
			prerrequisiteId: 3,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 4,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 12,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 4,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 14,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 1,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 3,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 16,
			prerrequisiteId: 3,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 4,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 5,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 7,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 9,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 14,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 17,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 4,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 5,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 6,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 18,
			prerrequisiteId: 6,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 1,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 13,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 19,
			prerrequisiteId: 13,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 22,
			prerrequisiteId: 15,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 22,
			prerrequisiteId: 15,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 9,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 12,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 14,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 4,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 5,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 7,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 12,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 21,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 1,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 3,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 11,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 23,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 17,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 18,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 20,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 6,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 9,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 14,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 15,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 17,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 25,
			prerrequisiteId: 20,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 16,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 17,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 21,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 9,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 12,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 14,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 17,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 26,
			prerrequisiteId: 21,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 8,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 23,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 19,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 8,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 27,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 6,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 11,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 19,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 1,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 3,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 13,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 6,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 28,
			prerrequisiteId: 19,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 18,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 28,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 4,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 5,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 6,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 19,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 29,
			prerrequisiteId: 28,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 16,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 23,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 30,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 16,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 23,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 31,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 30,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 31,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 23,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 33,
			prerrequisiteId: 31,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 25,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 30,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 20,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 23,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 25,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 34,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 25,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 30,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 31,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 20,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 23,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 25,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 35,
			prerrequisiteId: 31,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 24,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 25,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 26,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 29,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 16,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 17,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 2,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 20,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 21,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 10,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 21,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 22,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 28,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 1,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 2,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 3,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 4,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 5,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 6,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 7,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 8,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 10,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 12,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 13,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 15,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 16,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 17,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 19,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 20,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 21,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 22,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 23,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 24,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 25,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 26,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 27,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 28,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 29,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 30,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 31,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 33,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 34,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 32,
			prerrequisiteId: 35,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 17,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 21,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 37,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 9,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 11,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 12,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 14,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 18,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 22,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 17,
			completionId: 7,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 21,
			completionId: 7,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 37,
			completionId: 7,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 9,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 12,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 14,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 36,
			prerrequisiteId: 22,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 11,
			completionId: 7,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 1,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 3,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 6,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 13,
			completionId: 8,
			type: "C"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 11,
			completionId: 8,
			type: "F"
		}, {
			__typename: "CoursePrerrequisitesObj",
			courseId: 37,
			prerrequisiteId: 18,
			completionId: 8,
			type: "F"
	}];

  export const careerPlan = {
			__typename: "CareerPlanObj",
			id: 2,
			name: "Analista Universitario en Sistemas (UTN - FRBA)",
			courses: [{
				id: 1,
				name: "Analisis Matemático",
				year: 1,
				__typename: "CourseObj"
			}, {
				id: 2,
				name: "Ingeniería y Sociedad",
				year: 1,
				__typename: "CourseObj"
			}, {
				id: 3,
				name: "\u00c1lgebra y Geometría Analítica",
				year: 1,
				__typename: "CourseObj"
			}, {
				id: 4,
				name: "Matemática Discreta",
				year: 1,
				__typename: "CourseObj"
			}, {
				id: 5,
				name: "Algoritmos y Estructura de Datos",
				year: 1,
				__typename: "CourseObj"
			}, {
				id: 6,
				name: "Arquitectura de Computadoras",
				year: 1,
				__typename: "CourseObj"
			}, {
				id: 7,
				name: "Sistemas y Organizaciones",
				year: 1,
				__typename: "CourseObj"
			}, {
				id: 9,
				name: "Análisis de Sistemas",
				year: 2,
				__typename: "CourseObj"
			}, {
				id: 11,
				name: "Análisis Matemático II",
				year: 2,
				__typename: "CourseObj"
			}, {
				id: 12,
				name: "Sintaxis y Semántica de los Lenguajes",
				year: 2,
				__typename: "CourseObj"
			}, {
				id: 13,
				name: "Física I",
				year: 2,
				__typename: "CourseObj"
			}, {
				id: 14,
				name: "Paradigmas de Programación",
				year: 2,
				__typename: "CourseObj"
			}, {
				id: 15,
				name: "Inglés I",
				year: 2,
				__typename: "CourseObj"
			}, {
				id: 16,
				name: "Probabilidad y Estadística",
				year: 2,
				__typename: "CourseObj"
			}, {
				id: 17,
				name: "Diseño de Sistemas",
				year: 3,
				__typename: "CourseObj"
			}, {
				id: 18,
				name: "Sistemas Operativos",
				year: 3,
				__typename: "CourseObj"
			}, {
				id: 20,
				name: "Economía",
				year: 3,
				__typename: "CourseObj"
			}, {
				id: 21,
				name: "Gestión de Datos",
				year: 3,
				__typename: "CourseObj"
			}, {
				id: 22,
				name: "Inglés II",
				year: 3,
				__typename: "CourseObj"
			}, {
				id: 36,
				name: "Habilitación Profesional (Titulo int. sistemas)",
				year: 4,
				__typename: "CourseObj"
			}, {
				id: 37,
				name: "Comunicaciones y Redes",
				year: 4,
				__typename: "CourseObj"
			}]
};
